#ifndef RM_RAWMEDIA_INTERNAL_H
#define RM_RAWMEDIA_INTERNAL_H

#include <libavcodec/avcodec.h>

// Formats decoded by decoder and expected by encoder
#define RAWMEDIA_VIDEO_DECODE_PIXEL_FORMAT PIX_FMT_RGB24
#define RAWMEDIA_AUDIO_SAMPLE_FMT AV_SAMPLE_FMT_S16
#define RAWMEDIA_AUDIO_SAMPLE_RATE 44100
#define RAWMEDIA_AUDIO_CHANNEL_LAYOUT AV_CH_LAYOUT_STEREO
#define RAWMEDIA_AUDIO_SILENCE 0
#define RAWMEDIA_AUDIO_TIME_BASE ((AVRational){1, RAWMEDIA_AUDIO_SAMPLE_RATE})

#define RAWMEDIA_VIDEO_CODEC CODEC_ID_RAWVIDEO
#define RAWMEDIA_AUDIO_CODEC CODEC_ID_PCM_S16LE
#define RAWMEDIA_VIDEO_ENCODE_PIXEL_FORMAT PIX_FMT_UYVY422

#define INVALID_STREAM -1

#endif
